"""Prevent duplicate workout names

Revision ID: 038b4f8b56c5
Revises: 4a988dbfdf73
Create Date: 2026-09-05 23:57:33.060484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038b4f8b56c5'
down_revision: Union[str, Sequence[str], None] = '4a988dbfdf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_workout_user_name', 'workouts', ['user_id', 'name'])
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_workout_user_name",
            ["user_id", "name"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_workout_user_name', 'workouts', type_='unique')
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_workout_user_name",
            type_="unique",
        )

    # ### end Alembic commands ###
