"""Prevent duplicate exercise sets

Revision ID: 1a8cf9bb15dc
Revises: f911a75bd5b6
Create Date: 2026-09-06 18:30:35.341919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8cf9bb15dc'
down_revision: Union[str, Sequence[str], None] = 'f911a75bd5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_exercise_set_number', 'exercise_sets', ['session_id', 'exercise_id', 'set_number'])
   
    # for sqlite
    with op.batch_alter_table("exercise_sets", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_exercise_set_number",
            ["session_id", "exercise_id", "set_number"],
        )

   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_exercise_set_number', 'exercise_sets', type_='unique')

    # for sqlite
    with op.batch_alter_table("exercise_sets", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_exercise_set_number",
            type_="unique",
        )

    # ### end Alembic commands ###
