"""add exercise sets

Revision ID: f911a75bd5b6
Revises: ab313cd97bf4
Create Date: 2026-09-06 18:21:14.634673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f911a75bd5b6'
down_revision: Union[str, Sequence[str], None] = 'ab313cd97bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('weight_unit', sa.Enum('kg', 'lb', name='weightunit'), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('assistance_weight', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('assistance_weight_unit', sa.Enum('kg', 'lb', name='weightunit'), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_sets')
    # ### end Alembic commands ###
